name: Kafka Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kafka-test:
    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181
        options: >-
          --health-cmd="echo ruok | nc -w 3 localhost 2181 | grep imok"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=3
      kafka:
        image: confluentinc/cp-kafka:latest
        ports:
          - 9092:9092
        options: >-
          --health-cmd="nc -z localhost 9092"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=5
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup .NET environment
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build Application
      run: dotnet build --configuration Release

    # Step 5: Run unit tests
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal

    # Step 6: Run Kafka integration tests
    - name: Run Kafka Integration Tests
      run: |
        dotnet run --project ./src/KafkaDockerDemo.csproj --configuration Release
      env:
        KAFKA_BROKER: localhost:9092